# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Admin(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(339, 416)
        Form.setMinimumSize(QtCore.QSize(339, 416))
        Form.setMaximumSize(QtCore.QSize(339, 416))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 61, 16))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(0, 20, 341, 401))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Admin"))
        self.label.setText(_translate("Form", "Kullanıcılar:"))