# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Main(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(339, 416)
        Form.setMinimumSize(QtCore.QSize(339, 416))
        Form.setMaximumSize(QtCore.QSize(339, 416))
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 50, 91, 91))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 270, 91, 91))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Giriş"))
        self.pushButton.setText(_translate("Form", "Kullanıcı Kayıt"))
        self.pushButton_2.setText(_translate("Form", "Admin Girişi"))